### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by boustrophedon** [comment]
Sorry for the delay in getting to these reviews. Everything looks good, I'm just trying to figure out how to get github actions to run on PRs without having them run automatically.

**Comment by Kijewski** [comment]
No problem! If you want, I could have a look, too. I am using your project in https://github.com/Kijewski/pyextrasafe, and you could mostly just copy its ci.yml, just exclude the python specific rules (python-black + python-make).

**Comment by boustrophedon** [comment]
I updated some settings and enabled CI on PR. Could you test that it works by changing the comment above `ctx.add_arch` in this commit to something like

```
        // add_arch returns whether the arch has already been added.
        // Since this is a new context, it can be ignored.
        let _: bool = ctx.add_arch(ScmpArch::Native)?;
```

Thanks!

**Comment by Kijewski** [comment]
I rebased my PRs on the new HEAD. Because I'm a new contributor to this project, you still need to push a button to run the CI. Once a commit of  a user is accepted, all their subsequent workflow runs should start automatically.

**Comment by boustrophedon** [comment]
Whoops, the new contributors one was one of the settings I changed. It's running now.

**Review by boustrophedon — APPROVED** [review]

**Comment by boustrophedon** [comment]
Thanks again! I'll check out pyextrasafe soon!

**Comment by Kijewski** [comment]
Thank you very much for your project and merging my PRs!

I don't know if pyextrasafe will be interesting for anyone but me.
I use extrasafe for all my rust projects: Read the configuration, open a TCP or Unix socket (development vs production), start up tokio, and then lock down everything. I know my program, won't need to open another file, another socket, etc. 

In python you have to assume that the program reads files at random points, and starts threads randomly. But at least I can be sure that my program won't exfiltrate any data, because it won't open a file for writing or open a socket.

**Pull request merged**
